### ISSUE TITLE
<SOLVED>It doesn't work in Linux

### ISSUE THREAD

**Issue by rahadian** [DrakeWitt/steam-yellow#10]
it doesnt work. Appear error notify in my terminal .

> /home/tux/Documents/steam-yellow-master/index.js:30
> 	let username = answer;
> 	^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3

I will happy if you can help to solve it. thanks before.

**Comment by rahadian** [comment]
oke. now work.
I modified your index.js in part username and password, 

> // Prompt for username
> rl.question('Username? ', (answer) => {
> 
> username = answer;
> rl.question('Password? ', (answer) => {
>          password = answer;
>         const logOnOptions = {
>         accountName: username,
>         password: password
>                 };
>

**Comment by DahliaWitt** [comment]
What version of node are you using?

**Comment by rahadian** [comment]
v4.2.6

**Comment by InfamousChloe** [comment]
Try updating to at least LTS Version v6.9.2

**Comment by birjj** [comment]
Should probably close this instead of renaming it to \<SOLVED> :wink:
