### ISSUE TITLE
pm2

### ISSUE THREAD

**Issue by max324595** [DrakeWitt/steam-yellow#11]
How to pm2 "this" for all time working? (Debian)
Mabe you make this script 2FA?

**Comment by InfamousChloe** [comment]
It already supports 2FA?

**Comment by max324595** [comment]
No. I'd like to script could work all the time in pm2 and support Shared Secret.

**Comment by aVitomin** [comment]
+1 PM2 + 2FA

**Comment by birjj** [comment]
With #16 this can be done by doing

```bash
$ pm2 start index -- ./login.json
```

Assuming `./login.json` exists and is of the format described in the README.
