### ISSUE TITLE
Current version makes VR, logged in by web, and possibly mobile symbol appear.

### ISSUE THREAD

**Issue by Toybasher** [DrakeWitt/steam-yellow#13]
Previous versions did not make it say I was running in VR. This one does. Can it be fixed?

**Comment by InfamousChloe** [comment]
Until the pull request is accepted, find this in index.js:
`"persona_state_flags": 3847, // This makes it yellow`

and change it to:

`"persona_state_flags": 4, // This makes it yellow`
