### ISSUE TITLE
Strict mode issue

### ISSUE THREAD

**Issue by crazyredd** [DrakeWitt/steam-yellow#15]
The current index.js file doesn't enforce strict mode, this crashes the program.

Just put this at the top of the file:
"use strict";
That will allow you to use things like 'let' ect.

**Comment by LWSS** [comment]
or just delete the instances of let and it still works, that's what I did

**Comment by tominal** [comment]
"use strict"; works, deleting instances of let doesn't for me.

**Comment by birjj** [comment]
What version of Node are you guys using? What error are you specifically getting?
