### ISSUE TITLE
All steam games have high ping + boomerang

### ISSUE THREAD

**Issue by 14putlandl** [DrakeWitt/steam-yellow#21]
Hi, after using this and going to play csgo, I started glitching about and barely being in control of the game. I also tested this on chivalry to see if it was the same and it was. So, I stopped it from running but it was still the same. Then I uninstalled node to attempt to stop anything from happening. This made little to no effect, so I reinstalled it and then updated a few things with node. Whilst games are now playable, I can still see an obvious performance difference. What can I do to fix this, as stuff is pretty difficult to play.

**Comment by prism2001** [comment]
why are you even using this program? it says in huge text on the repo page that it doesn't work anymore.

**Comment by DahliaWitt** [comment]
This repo has been dead since January 2017 when Valve patched the yellow flag. If you are still getting bad performance with NodeJS uninstalled then it is something else affecting your computer. The program is simply a script to run with Node.
