### ISSUE TITLE
Change the colour?

### ISSUE THREAD

**Issue by nutterdk** [DrakeWitt/steam-yellow#4]
AS the title says... can we change the colour to something new? and if this gets patched you need to code around it

**Comment by zer0sec** [comment]
i'd also like to see this

**Comment by outlassn** [comment]
This is probably not possible, as all the tool does is set your flag to one for holidays (or something like that, i dont know the exact specifics), and other color flags have not been found yet, or do not exist at the current time.

**Comment by Kefta** [comment]
@nutterdk It will be patched pretty soon, and yellow is the only "unique" colour that can be selected aside from the standard gray, blue, and green due to the colours being related by flags and not a strict selector.

**Comment by patkub** [comment]
@nutterdk the flags are private. Only "personastate" is public, so you can force online, away, etc. https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

**Comment by DahliaWitt** [comment]
Unfortunately this is not possible. This tool utilizes a gold color valve left behind for a holiday event.
