### ISSUE TITLE
<SOLVED> Syntax error

### ISSUE THREAD

**Issue by LordPh** [DrakeWitt/steam-yellow#5]
When i try to login i get some error

**Comment by DahliaWitt** [comment]
Please provide the error you get. I can't do much without it.

**Comment by LordPh** [comment]
http://imgur.com/COyh8Q9

**Comment by InfamousChloe** [comment]
Did you install node.js and type the commands into CMD? You shouldn't be double clicking any of the files.

**Comment by LordPh** [comment]
IT worked first time,i followed this guy's tutorial https://www.youtube.com/watch?v=337khh_8WJ4

**Comment by LordPh** [comment]
I SOLVED IT THANKS ANYWAY
