### ISSUE TITLE
"NPM" is not recognized

### ISSUE THREAD

**Issue by StrandTheRand** [DrakeWitt/steam-yellow#9]
C:\steam-yellow>npm install
'npm' is not recognized as an internal or external command,
operable program or batch file. 
I already have node installed but it still will not install

**Comment by InfamousChloe** [comment]
Either restart or:
Open the Control Panel (Click the Start button, then click Control Panel)
Click User Accounts
Click Change my environment variables
Select PATH and click the Edit... button
At the end of the Variable value, add ;C:\Program Files\nodejs
Click Ok on the "Edit User Variable" window, then click Ok on the "Environment Variables" window

**Comment by StrandTheRand** [comment]
It now works but it installs for about a second then stops installing.
![d62f9fb3000abcc6a48ade0ae2f18abd](https://cloud.githubusercontent.com/assets/24886774/21600580/4652bc26-d1ca-11e6-81bd-1294e40ceb92.gif)

**Comment by DahliaWitt** [comment]
Will it let you start the program?

**Comment by BenVlodgi** [comment]
looks like its starting for a half second in the gif

**Comment by InfamousChloe** [comment]
Yes, npm install looks like it's starting but what about node index.js?

**Comment by DahliaWitt** [comment]
Batch file in new version should take care of npm install.
